# Generated by Django 5.0 on 2024-02-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_moviplus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
